# Generated by Django 3.2.9 on 2021-12-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_failed_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failed_login',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
