# Generated by Django 3.2.9 on 2022-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_permission_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_classes',
            field=models.ManyToManyField(to='accounts.Permission'),
        ),
    ]
