# Generated by Django 3.2.9 on 2022-01-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220103_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission_classes',
        ),
        migrations.RemoveField(
            model_name='user_prmissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user_prmissions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='user_prmissions',
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
    ]
