# Generated by Django 3.2.9 on 2022-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220125_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='make_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
